;constants
SFX_BANK equ 08h
SFX_BANK_OFFSET equ 0B000h			
DAC_BANK_1 equ 03Ch
DAC_BANK_2 equ 03Dh
MUSIC_BANK_1 equ 03Fh				
MUSIC_BANK_2 equ 03Eh
YM_INSTRUMENTS_BANK equ 03Dh
YM_INSTRUMENTS_BANK_OFFSET equ 0B000h		

;offsets
STACK_START equ 1FE0h

SAVED_MUSIC_BANK 	equ 1FE0h
MUSIC_BANK 		equ 1FF0h	
PREVIOUS_MUSIC 		equ 1FE1h
CURRENT_MUSIC 		equ 1FF1h
SAVED_YM_TIMER_VALUE 	equ 1FE2h
YM_TIMER_VALUE 		equ 1FF2h
SAVED_MUSIC_DOESNT_USE_SAMPLES equ 1FE3h
MUSIC_DOESNT_USE_SAMPLES equ 1FF3h
	
NEW_SAMPLE_TO_LOAD 	equ 1FE4h
DAC_BANK		equ 1FF4h
DAC_LAST_OFFSET 	equ 1FE5h
DAC_REMAINING_LENGTH 	equ 1FF5h
		
RESUMING_DEACTIVATED	equ 1FE8h

FADE_OUT_LENGTH		equ 1FEBh
FADE_OUT_TIMER		equ 1FECh
FADE_OUT_COUNTER	equ 1FEDh
CURRENTLY_FADING_OUT	equ 1FEEh

FADE_IN_TIMER		equ 1FFBh
FADE_IN_PARAMETERS 	equ 1FFCh	
MUSIC_LEVEL 		equ 1FFDh

LAST_COMMAND 		equ 1FFEh	
COMMANDS_COUNTER 	equ 1FEFh
NEW_OPERATION 		equ 1FFFh
					

;registers
YM1_REGISTER equ 4000h
YM1_DATA equ 4001h
YM2_REGISTER equ 4002h
YM2_DATA equ 4003h
BANK_REGISTER equ 6000h
PSG_PORT equ 7F11h